name: Magento Community Edition Docker container build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - PHP_VERSION: php7-fpm
            MAGENTO_VERSION: 2.0.18
          - PHP_VERSION: php7-fpm
            MAGENTO_VERSION: 2.1.18
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.1.18
          - PHP_VERSION: php7-fpm
            MAGENTO_VERSION: 2.2.9
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.2.9
          - PHP_VERSION: php7-fpm
            MAGENTO_VERSION: 2.2.10
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.2.10
          - PHP_VERSION: php7-fpm
            MAGENTO_VERSION: 2.2.11
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.2.11
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.0
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.0
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.1
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.1
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.2
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.2
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.3
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.3
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.3
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.4
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.4
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.4
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.5-p1
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.5-p1
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.5-p1
          - PHP_VERSION: php71-fpm
            MAGENTO_VERSION: 2.3.5-p2
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.5-p2
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.5-p2
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.4.0
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.4.0
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run:
        docker build magento
        -t michielgerritsen/magento-project-community-edition:${{ matrix.PHP_VERSION }}-magento${{ matrix.MAGENTO_VERSION }}
        --build-arg MAGENTO_VERSION=${{ matrix.MAGENTO_VERSION }}
        --build-arg PHP_VERSION=${{ matrix.PHP_VERSION }}

    - name: Docker hub login
      if: github.ref == 'refs/heads/build'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the image to Docker hub
      if: github.ref == 'refs/heads/build'
      run: docker push michielgerritsen/magento-project-community-edition
